"""Compile VELA source to Python (kernel-backed)."""
from __future__ import annotations

from pathlib import Path

from vela.ast import Program
from vela.checker import check
from vela.ir import VelaConfig, program_to_config
from vela.parser import parse


PY_TEMPLATE = '''\
# Generated by VELA {version} from {src_name}
# Controller: {name}
# Mechanisms: {mechs}
# Do not claim dual-gate wins from this file. Run: py -3 -m vela eval

from __future__ import annotations

from vela.ir import VelaConfig
from vela.kernel import HorizonCCA, make_cca

VELA_CONFIG = VelaConfig(
    name={name!r},
    mechanisms={mechs!r},
    posture={posture!r},
    observe_only={observe},
    passthrough={passthrough},
    predictive_freeze={pred},
    interval_bw={ibw},
    horizon_chase={chase},
    typed_loss={tloss},
    dual_gate_guard={gate},
    oce_legacy={oce},
    freeze_lead_rtts={lead},
    chase_rtts={crtt},
    chase_bdp_div={cdiv},
    rollback_delay={rb},
    trim_hold={thold},
    trim_fill={tfill},
    trim_reclaim={trec},
    quiet_reach={qreach},
    quiet_shield={qshield},
    soft_flicker={sflick},
    seeds={seeds!r},
    scenarios={scen!r},
    duration_s={dur},
    baseline={base!r},
    contract_name={cname!r},
    reports={reports!r},
    cuts_compose={cuts!r},
    jain_min={jain},
    no_oracle={oracle},
)

CCA_NAME = {name!r}


def make():
    return HorizonCCA(VELA_CONFIG)


factory = make_cca(VELA_CONFIG)
'''


def compile_program(prog: Program, *, strict: bool = True) -> tuple[str, VelaConfig]:
    result = check(prog)
    if strict:
        result.raise_if_error()
    cfg = program_to_config(prog)
    from vela import __version__

    text = PY_TEMPLATE.format(
        version=__version__,
        src_name=prog.source_name,
        name=cfg.name,
        mechs=cfg.mechanisms,
        posture=cfg.posture,
        observe=cfg.observe_only,
        passthrough=cfg.passthrough,
        pred=cfg.predictive_freeze,
        ibw=cfg.interval_bw,
        chase=cfg.horizon_chase,
        tloss=cfg.typed_loss,
        gate=cfg.dual_gate_guard,
        oce=cfg.oce_legacy,
        lead=cfg.freeze_lead_rtts,
        crtt=cfg.chase_rtts,
        cdiv=cfg.chase_bdp_div,
        rb=cfg.rollback_delay,
        thold=cfg.trim_hold,
        tfill=cfg.trim_fill,
        trec=cfg.trim_reclaim,
        qreach=cfg.quiet_reach,
        qshield=cfg.quiet_shield,
        sflick=cfg.soft_flicker,
        seeds=cfg.seeds,
        scen=cfg.scenarios,
        dur=cfg.duration_s,
        base=cfg.baseline,
        cname=cfg.contract_name,
        reports=cfg.reports,
        cuts=cfg.cuts_compose,
        jain=cfg.jain_min,
        oracle=cfg.no_oracle,
    )
    return text, cfg


def compile_source(src: str, name: str = "<input>", *, strict: bool = True) -> tuple[str, VelaConfig]:
    prog = parse(src, name)
    return compile_program(prog, strict=strict)


def compile_file(path: str | Path, out: str | Path | None = None, *, strict: bool = True) -> Path:
    path = Path(path)
    text, cfg = compile_source(path.read_text(encoding="utf-8"), str(path), strict=strict)
    if out is None:
        out = Path("emit") / f"{cfg.name.lower()}_cca.py"
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
    return out
