"""Emit a Rust-shaped IR sketch (not a production QUIC controller)."""
from __future__ import annotations

from vela.ast import Program
from vela.checker import (
    controller_has_typed_loss,
    controller_has_typed_reconfig,
    controller_is_passthrough,
)
from vela.ir import program_to_config
from vela.types import HOUSE_ENDPOINT_CUT, review_writes_in


class EmitRustError(ValueError):
    """Closed-write under observe must not ship as a Rust IR bind."""


def _rust_bool(value: bool) -> str:
    return "true" if value else "false"


def emit_rust(prog: Program) -> str:
    """Lower a checked program to an honesty-preserving Rust IR sketch.

    The Mech enum is a catalog of named stdlib operators. Listing HorizonChase
    in the enum does not enable it. Observe-only Reach must stamp
    observe_only=true and closed-write flags false so a port cannot pretend
    a review compose shipped as the flagship.

    Under posture observe, closed-write / review-write operators in compose
    are refused here (checker already errors; this is the emit bind).
    """
    if not prog.controllers:
        raise EmitRustError("emit_rust: program has no controller")
    ctrl = prog.controllers[0]
    sneaks = review_writes_in(ctrl.compose)
    if ctrl.posture == "observe" and sneaks:
        raise EmitRustError(
            f"{ctrl.name}: refuse emit-rust under posture observe with "
            f"closed-write {sneaks}; use posture review or drop them"
        )

    cfg = program_to_config(prog)
    # Defense in depth: observe bind clears write flags even if compose lied.
    if cfg.posture == "observe":
        cfg.horizon_chase = False
        cfg.soft_flicker = False
        cfg.quiet_reach = False
        cfg.quiet_shield = False
        cfg.trim_hold = False
        cfg.trim_fill = False
        cfg.trim_reclaim = False
        cfg.oce_legacy = False
        cfg.observe_only = True

    typed_reconfig = controller_has_typed_reconfig(ctrl)
    typed_loss = controller_has_typed_loss(ctrl)
    passthrough = controller_is_passthrough(ctrl)
    # Prefer checker-derived passthrough; IR may lag if compose was filtered.
    if cfg.posture == "observe" and cfg.observe_only:
        cfg.passthrough = passthrough

    mechs = ",\n        ".join(f"Mech::{m}" for m in cfg.mechanisms)
    observe = _rust_bool(cfg.observe_only)
    passthrough_s = _rust_bool(passthrough)
    chase = _rust_bool(cfg.horizon_chase)
    soft_flicker = _rust_bool(cfg.soft_flicker)
    quiet_reach = _rust_bool(cfg.quiet_reach)
    typed_reconfig_s = _rust_bool(typed_reconfig)
    typed_loss_s = _rust_bool(typed_loss)
    posture = cfg.posture
    house_cut = HOUSE_ENDPOINT_CUT
    honesty = (
        "IR sketch only. Not a QUIC controller. "
        "Mech enum is a catalog; CONFIG flags are the bind. "
        "Observe-only Reach must keep closed-write flags false. "
        "SoftReprobe house cut is 0.58 on RttHop and Flicker. "
        "Do not claim a dual-gate win from this file."
    )
    return f"""// Generated by VELA. {honesty}
// Porting this to quiche/quinn still needs a real ACK clock and loss signal.
// Controller: {cfg.name}
// posture={posture} observe_only={observe} passthrough={passthrough_s}
// typed_reconfig={typed_reconfig_s} typed_loss={typed_loss_s} house_cut={house_cut}

#![allow(dead_code)]

/// Catalog of named stdlib operators. Presence in the enum is not enablement.
#[derive(Clone, Copy, Debug)]
pub enum Mech {{
    Detect,
    SoftReprobe,
    IntervalBw,
    PredictiveFreeze,
    HorizonChase,
    DualGateGuard,
    OCE,
    TypedLoss,
    FairMode,
    Calendar,
    WriteBudget,
    TrimHold,
    TrimFill,
    TrimReclaim,
    QuietReach,
    QuietShield,
    SoftFlicker,
}}

#[derive(Clone, Debug)]
pub struct VelaConfig {{
    pub name: &'static str,
    pub mechs: &'static [Mech],
    pub posture: &'static str,
    pub observe_only: bool,
    pub passthrough: bool,
    pub typed_reconfig: bool,
    pub typed_loss: bool,
    pub house_endpoint_cut: f64,
    pub horizon_chase: bool,
    pub soft_flicker: bool,
    pub quiet_reach: bool,
    pub freeze_lead_rtts: f64,
    pub chase_rtts: f64,
    pub chase_bdp_div: f64,
    pub rollback_delay: f64,
}}

pub const CONFIG: VelaConfig = VelaConfig {{
    name: "{cfg.name}",
    mechs: &[
        {mechs}
    ],
    posture: "{posture}",
    observe_only: {observe},
    passthrough: {passthrough_s},
    typed_reconfig: {typed_reconfig_s},
    typed_loss: {typed_loss_s},
    house_endpoint_cut: {house_cut},
    horizon_chase: {chase},
    soft_flicker: {soft_flicker},
    quiet_reach: {quiet_reach},
    freeze_lead_rtts: {cfg.freeze_lead_rtts},
    chase_rtts: {cfg.chase_rtts},
    chase_bdp_div: {cfg.chase_bdp_div},
    rollback_delay: {cfg.rollback_delay},
}};

/// Sender-side surface a QUIC stack would call.
pub trait CongestionController {{
    fn on_ack(&mut self, t: f64, rtt_s: f64, bytes_acked: u64, lost: u64);
    fn on_loss(&mut self, t: f64, bytes_lost: u64, congestive: bool);
    fn can_send(&self, t: f64) -> u64;
}}

// Epoch-typed samples belong in the kernel, not in this sketch.
// Invalidating min_rtt on Reconfig is a type-level obligation of the VELA source.
// SoftReprobe cut stays {house_cut} on RttHop and Flicker; SoftFlicker is review.
"""
