"""Emit a Rust-shaped IR sketch (not a production QUIC controller)."""
from __future__ import annotations

from vela.ast import Program
from vela.ir import program_to_config


def emit_rust(prog: Program) -> str:
    cfg = program_to_config(prog)
    mechs = ",\n        ".join(f'Mech::{m}' for m in cfg.mechanisms)
    return f"""// Generated by VELA. IR sketch only.
// Porting this to quiche/quinn still needs a real ACK clock and loss signal.
// Controller: {cfg.name}

#![allow(dead_code)]

#[derive(Clone, Copy, Debug)]
pub enum Mech {{
    Detect,
    SoftReprobe,
    IntervalBw,
    PredictiveFreeze,
    HorizonChase,
    DualGateGuard,
    OCE,
    TypedLoss,
    FairMode,
}}

#[derive(Clone, Debug)]
pub struct VelaConfig {{
    pub name: &'static str,
    pub mechs: &'static [Mech],
    pub freeze_lead_rtts: f64,
    pub chase_rtts: f64,
    pub chase_bdp_div: f64,
    pub rollback_delay: f64,
}}

pub const CONFIG: VelaConfig = VelaConfig {{
    name: "{cfg.name}",
    mechs: &[
        {mechs}
    ],
    freeze_lead_rtts: {cfg.freeze_lead_rtts},
    chase_rtts: {cfg.chase_rtts},
    chase_bdp_div: {cfg.chase_bdp_div},
    rollback_delay: {cfg.rollback_delay},
}};

/// Sender-side surface a QUIC stack would call.
pub trait CongestionController {{
    fn on_ack(&mut self, t: f64, rtt_s: f64, bytes_acked: u64, lost: u64);
    fn on_loss(&mut self, t: f64, bytes_lost: u64, congestive: bool);
    fn can_send(&self, t: f64) -> u64;
}}

// Epoch-typed samples belong in the kernel, not in this sketch.
// Invalidating min_rtt on Reconfig is a type-level obligation of the VELA source.
"""
