"""Emit a Rust-shaped IR sketch (not a production QUIC controller)."""
from __future__ import annotations

from vela.ast import Program
from vela.ir import program_to_config


def _rust_bool(value: bool) -> str:
    return "true" if value else "false"


def emit_rust(prog: Program) -> str:
    """Lower a checked program to an honesty-preserving Rust IR sketch.

    The Mech enum is a catalog of named stdlib operators. Listing HorizonChase
    in the enum does not enable it. Observe-only Reach must stamp
    observe_only=true and closed-write flags false so a port cannot pretend
    a review compose shipped as the flagship.
    """
    cfg = program_to_config(prog)
    mechs = ",\n        ".join(f"Mech::{m}" for m in cfg.mechanisms)
    observe = _rust_bool(cfg.observe_only)
    passthrough = _rust_bool(cfg.passthrough)
    chase = _rust_bool(cfg.horizon_chase)
    soft_flicker = _rust_bool(cfg.soft_flicker)
    quiet_reach = _rust_bool(cfg.quiet_reach)
    posture = cfg.posture
    honesty = (
        "IR sketch only. Not a QUIC controller. "
        "Mech enum is a catalog; CONFIG flags are the bind. "
        "Observe-only Reach must keep closed-write flags false. "
        "Do not claim a dual-gate win from this file."
    )
    return f"""// Generated by VELA. {honesty}
// Porting this to quiche/quinn still needs a real ACK clock and loss signal.
// Controller: {cfg.name}
// posture={posture} observe_only={observe} passthrough={passthrough}

#![allow(dead_code)]

/// Catalog of named stdlib operators. Presence in the enum is not enablement.
#[derive(Clone, Copy, Debug)]
pub enum Mech {{
    Detect,
    SoftReprobe,
    IntervalBw,
    PredictiveFreeze,
    HorizonChase,
    DualGateGuard,
    OCE,
    TypedLoss,
    FairMode,
    Calendar,
    WriteBudget,
    TrimHold,
    TrimFill,
    TrimReclaim,
    QuietReach,
    QuietShield,
    SoftFlicker,
}}

#[derive(Clone, Debug)]
pub struct VelaConfig {{
    pub name: &'static str,
    pub mechs: &'static [Mech],
    pub posture: &'static str,
    pub observe_only: bool,
    pub passthrough: bool,
    pub horizon_chase: bool,
    pub soft_flicker: bool,
    pub quiet_reach: bool,
    pub freeze_lead_rtts: f64,
    pub chase_rtts: f64,
    pub chase_bdp_div: f64,
    pub rollback_delay: f64,
}}

pub const CONFIG: VelaConfig = VelaConfig {{
    name: "{cfg.name}",
    mechs: &[
        {mechs}
    ],
    posture: "{posture}",
    observe_only: {observe},
    passthrough: {passthrough},
    horizon_chase: {chase},
    soft_flicker: {soft_flicker},
    quiet_reach: {quiet_reach},
    freeze_lead_rtts: {cfg.freeze_lead_rtts},
    chase_rtts: {cfg.chase_rtts},
    chase_bdp_div: {cfg.chase_bdp_div},
    rollback_delay: {cfg.rollback_delay},
}};

/// Sender-side surface a QUIC stack would call.
pub trait CongestionController {{
    fn on_ack(&mut self, t: f64, rtt_s: f64, bytes_acked: u64, lost: u64);
    fn on_loss(&mut self, t: f64, bytes_lost: u64, congestive: bool);
    fn can_send(&self, t: f64) -> u64;
}}

// Epoch-typed samples belong in the kernel, not in this sketch.
// Invalidating min_rtt on Reconfig is a type-level obligation of the VELA source.
// SoftReprobe cut stays 0.58 on RttHop and Flicker; SoftFlicker is review.
"""
